// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebCourseManagement_Models.DataContexts;

#nullable disable

namespace WebCourseManagement_Models.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240301073203_upv3")]
    partial class upv3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebCourseManagement_Models.Entities.BaiHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChuongKhoaHocId")
                        .HasColumnType("int");

                    b.Property<int>("LoaiBaiHocId")
                        .HasColumnType("int");

                    b.Property<string>("MoTaBaiHoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenBaiHoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ThoiGianCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("ThoiLuongVideo")
                        .HasColumnType("int");

                    b.Property<int>("TrangThaiBaiHocId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChuongKhoaHocId");

                    b.HasIndex("LoaiBaiHocId");

                    b.HasIndex("TrangThaiBaiHocId");

                    b.ToTable("baiHocs");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.BaiViet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnhBaiViet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DuLieuBaiViet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTaBaiViet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NguoiDungTaoBaiId")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongThich")
                        .HasColumnType("int");

                    b.Property<int>("SoLuotBinhLuan")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ThoiGianCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianXoa")
                        .HasColumnType("datetime2");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThaiBaiVietId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NguoiDungTaoBaiId");

                    b.HasIndex("TrangThaiBaiVietId");

                    b.ToTable("baiViets");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.BaoCao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BinhLuanId")
                        .HasColumnType("int");

                    b.Property<bool>("DaViPham")
                        .HasColumnType("bit");

                    b.Property<bool>("DaXacMinh")
                        .HasColumnType("bit");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LoaiBaoCaoId")
                        .HasColumnType("int");

                    b.Property<int?>("LoaiBinhLuan")
                        .HasColumnType("int");

                    b.Property<int>("NguoiDungGuiId")
                        .HasColumnType("int");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<int?>("NguoiDungXacMinhId")
                        .HasColumnType("int");

                    b.Property<int>("NguoiViPhamId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianGuiBaoCao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianXacMinh")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LoaiBaoCaoId");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("baoCaos");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.BinhLuanBaiHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BaiHocId")
                        .HasColumnType("int");

                    b.Property<string>("BinhLuan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BinhLuanGocId")
                        .HasColumnType("int");

                    b.Property<string>("DuongDanAnhBinhLuan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<int>("SoLuotBinhLuanTraLoi")
                        .HasColumnType("int");

                    b.Property<int>("SoLuotLike")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ThoiGianCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianXoa")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrangThaiBinhLuanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BaiHocId");

                    b.HasIndex("NguoiDungId");

                    b.HasIndex("TrangThaiBinhLuanId");

                    b.ToTable("binhLuanBaiHocs");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.BinhLuanBaiViet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BaiVietId")
                        .HasColumnType("int");

                    b.Property<string>("BinhLuan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BinhLuanGocId")
                        .HasColumnType("int");

                    b.Property<string>("DuongDanAnhBinhLuan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<int>("SoLuotBinhLuanTraLoi")
                        .HasColumnType("int");

                    b.Property<int>("SoLuotLike")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ThoiGianCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianXoa")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrangThaiBinhLuanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BaiVietId");

                    b.HasIndex("NguoiDungId");

                    b.HasIndex("TrangThaiBinhLuanId");

                    b.ToTable("binhLuanBaiViets");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnhBlog")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LinkBlog")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LoaiBlogId")
                        .HasColumnType("int");

                    b.Property<int>("NguoiDangBaiId")
                        .HasColumnType("int");

                    b.Property<int>("SoLuotBinhLuan")
                        .HasColumnType("int");

                    b.Property<int>("SoLuotThich")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ThoiGianCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianXoa")
                        .HasColumnType("datetime2");

                    b.Property<string>("TieuDeBlog")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThaiBlogId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LoaiBlogId");

                    b.HasIndex("NguoiDangBaiId");

                    b.HasIndex("TrangThaiBlogId");

                    b.ToTable("blogs");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.ChuongKhoaHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("KhoaHocId")
                        .HasColumnType("int");

                    b.Property<int>("SoBaiHocTrongChuong")
                        .HasColumnType("int");

                    b.Property<string>("TenChuong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("TongThoiGianHoc1Chuong")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KhoaHocId");

                    b.ToTable("chuongKhoaHocs");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.ChuyenNganh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenChuyenNganh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("chuyenNganhs");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.CodeDaNgonNgu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CallTestCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodeKhoiDau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NgonNguId")
                        .HasColumnType("int");

                    b.Property<int>("ThucHanhId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NgonNguId");

                    b.HasIndex("ThucHanhId");

                    b.ToTable("codeDaNgonNgus");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.DanhHieu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenDanhHieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("danhHieus");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.DanhHieuNguoiDung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DanhHieuId")
                        .HasColumnType("int");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DanhHieuId");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("danhHieuNguoiDungs");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.DanhMucNguoiDung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("danhMucNguoiDungs");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.DatCauHoi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BaiHocId")
                        .HasColumnType("int");

                    b.Property<string>("CauHoi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CauTraLoiA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CauTraLoiB")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CauTraLoiC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CauTraLoiD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoCauTraLoi")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BaiHocId");

                    b.ToTable("datCauHois");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.DiemKiemTraBaiHocCuaNguoiDung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BaiHocId")
                        .HasColumnType("int");

                    b.Property<bool>("DaHoanThanh")
                        .HasColumnType("bit");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianMoBaiHoc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BaiHocId");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("diemKiemTraBaiHocCuaNguoiDungs");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.HoanThanhThucHanh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BaiHocThucHanhId")
                        .HasColumnType("int");

                    b.Property<int?>("NgonNguId")
                        .HasColumnType("int");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ThoiGianHoanThanh")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BaiHocThucHanhId");

                    b.HasIndex("NgonNguId");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("hoanThanhThucHanhs");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.HoanThanhTraLoiCauHoi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CauHoiId")
                        .HasColumnType("int");

                    b.Property<string>("CauTraLoi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ThoiGianHoanThanh")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CauHoiId");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("hoanThanhTraLoiCauHois");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.KhoaHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnhKhoaHoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("GiaKhoaHoc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LinkVideoGioiThieu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LoaiKhoaHocId")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiTaoId")
                        .HasColumnType("int");

                    b.Property<int>("SoBaiHoc")
                        .HasColumnType("int");

                    b.Property<int>("SoChuong")
                        .HasColumnType("int");

                    b.Property<int>("SoHocVienDaHoanThanh")
                        .HasColumnType("int");

                    b.Property<int>("SoNguoiDangKyKhoaHoc")
                        .HasColumnType("int");

                    b.Property<string>("TenKhoaHoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TongThoiGianBaiHoc")
                        .HasColumnType("int");

                    b.Property<int>("TrangThaiKhoaHocId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LoaiKhoaHocId");

                    b.HasIndex("NguoiTaoId");

                    b.HasIndex("TrangThaiKhoaHocId");

                    b.ToTable("khoaHocs");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.KhoaHocCuaNguoiDung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BaiHocId")
                        .HasColumnType("int");

                    b.Property<bool>("DaHoanThanh")
                        .HasColumnType("bit");

                    b.Property<int?>("KhoaHocId")
                        .HasColumnType("int");

                    b.Property<int?>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<double>("PhanTramHoanThanh")
                        .HasColumnType("float");

                    b.Property<DateTime>("ThoiGianDangKy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianHocLanCuoi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TienDoBaiHocId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BaiHocId");

                    b.HasIndex("KhoaHocId");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("khoaHocCuaNguoiDungs");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.KinhNghiem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChiTiet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianKetThuc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("kinhNghiems");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.KinhNghiemHocTap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChuyenNganhId")
                        .HasColumnType("int");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<int>("TruongHocId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChuyenNganhId");

                    b.HasIndex("NguoiDungId");

                    b.HasIndex("TruongHocId");

                    b.ToTable("kinhNghiemHocTaps");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.LienHe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("DaLienHe")
                        .HasColumnType("bit");

                    b.Property<int?>("DanhGiaTheoSao")
                        .HasColumnType("int");

                    b.Property<int?>("NguoiLienHeId")
                        .HasColumnType("int");

                    b.Property<string>("NoiDungDanhGia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNguoiLienHe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGianGuiYeuCau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianLienHe")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NguoiLienHeId");

                    b.ToTable("lienHes");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.LoaiBaiHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("loaiBaiHocs");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.LoaiBaoCao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenLoaiBaoCao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("loaiBaoCaos");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.LoaiBlog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenLoaiBlog")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("loaiBlogs");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.LoaiKhoaHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("loaiKhoaHocs");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.LoaiTruongHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("loaiTruongHocs");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.NgonNgu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenNgonNgu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ngonNgus");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.NguoiDung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnhDaiDien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("DaKhoa")
                        .HasColumnType("bit");

                    b.Property<int?>("DanhMucNguoiDungId")
                        .HasColumnType("int");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GioiTinh")
                        .HasColumnType("int");

                    b.Property<string>("HoVaTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<int?>("QuanHuyenId")
                        .HasColumnType("int");

                    b.Property<int>("QuyenHanId")
                        .HasColumnType("int");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SoLanViPham")
                        .HasColumnType("int");

                    b.Property<string>("TenTaiKhoan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ThoiGianCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianKhoa")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianMoKhoa")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TinhThanhId")
                        .HasColumnType("int");

                    b.Property<int>("TrangThaiNguoiDungId")
                        .HasColumnType("int");

                    b.Property<int?>("XaPhuongId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DanhMucNguoiDungId");

                    b.HasIndex("QuanHuyenId");

                    b.HasIndex("QuyenHanId");

                    b.HasIndex("TinhThanhId");

                    b.HasIndex("TrangThaiNguoiDungId");

                    b.HasIndex("XaPhuongId");

                    b.ToTable("nguoiDungs");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.NguoiDungGhiChuBaiHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DiemKiemTraBaiHocId")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGianGhiChu")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DiemKiemTraBaiHocId");

                    b.ToTable("nguoiDungGhiChus");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.NguoiDungThichBaiViet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BaiVietId")
                        .HasColumnType("int");

                    b.Property<bool>("DaXoa")
                        .HasColumnType("bit");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianThich")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BaiVietId");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("nguoiDungThichBaiViets");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.NguoiDungThichBinhLuanBaiHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BinhLuanBaiHocId")
                        .HasColumnType("int");

                    b.Property<bool>("DaXoa")
                        .HasColumnType("bit");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BinhLuanBaiHocId");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("nguoiDungThichBinhLuanBaiHocs");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.NguoiDungThichBinhLuanBaiViet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BinhLuanBaiVietId")
                        .HasColumnType("int");

                    b.Property<bool>("DaXoa")
                        .HasColumnType("bit");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BinhLuanBaiVietId");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("nguoiDungThichBinhLuanBaiViets");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.NoiDungTrangChu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slide1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slide2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slide3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slide4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slide5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("noiDungTrangChus");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.PhanHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BaiHocId")
                        .HasColumnType("int");

                    b.Property<int>("ChuongKhoaHocId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianThemBaiHocVaoPhanHoc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BaiHocId");

                    b.HasIndex("ChuongKhoaHocId");

                    b.ToTable("phanHocs");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.QuanHuyen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenQuanHuyen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenQuanHuyenEnglish")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TinhThanhId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TinhThanhId");

                    b.ToTable("quanHuyens");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.QuyenHan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MaQuyen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenQuyenHan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("quyenHans");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianHetHan")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("refreshTokens");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.TestCase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChiTietDauVao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodeDauVao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("KhoaTestCase")
                        .HasColumnType("bit");

                    b.Property<string>("MongDoiDauRa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ThucHanhId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ThucHanhId");

                    b.ToTable("testCases");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.ThongBao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("DaXem")
                        .HasColumnType("bit");

                    b.Property<bool>("HeThongThongBao")
                        .HasColumnType("bit");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NguoiDungGuiThongBaoId")
                        .HasColumnType("int");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("thongBaos");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.ThongBaoTrangChu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LinkAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("thongBaoTrangChus");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.ThucHanh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BaiHocId")
                        .HasColumnType("int");

                    b.Property<string>("CallTestCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChiTietVanDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodeDauVao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodeKhoiDau")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GiaiThich")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoiY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("HoTroDaNgonNgu")
                        .HasColumnType("bit");

                    b.Property<string>("MongDoiDauRa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NgonNguMacDinhId")
                        .HasColumnType("int");

                    b.Property<string>("VanDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BaiHocId");

                    b.HasIndex("NgonNguMacDinhId");

                    b.ToTable("thucHanhs");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.TinhThanh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenTinhThanh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenTinhThanhEnglish")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tinhThanhs");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.TrangThaiBaiHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenTrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("trangThaiBaiHocs");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.TrangThaiBaiViet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenTrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("trangThaiBaiViets");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.TrangThaiBinhLuan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenTrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("trangThaiBinhLuans");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.TrangThaiBlog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenTrangThaiBlog")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("trangThaiBlogs");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.TrangThaiKhoaHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenTrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("trangThaiKhoaHocs");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.TrangThaiNguoiDung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MaTrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenTrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("trangThaiNguoiDungs");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.TruongHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LoaiTruongHocId")
                        .HasColumnType("int");

                    b.Property<string>("TenTruongHoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LoaiTruongHocId");

                    b.ToTable("truongHocs");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.VideoBaiGiang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BaiHocId")
                        .HasColumnType("int");

                    b.Property<string>("LinkBaiHoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BaiHocId");

                    b.ToTable("videoBaiGiangs");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.VideoHoanThanh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianHoanThanh")
                        .HasColumnType("datetime2");

                    b.Property<int>("VideoBaiGiangId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NguoiDungId");

                    b.HasIndex("VideoBaiGiangId");

                    b.ToTable("videoHoanThanhs");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.XaPhuong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuanHuyenId")
                        .HasColumnType("int");

                    b.Property<string>("TenXaPhuong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenXaPhuongEnglish")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("QuanHuyenId");

                    b.ToTable("xaPhuongs");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.XacNhanEmail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("DaXacNhan")
                        .HasColumnType("bit");

                    b.Property<string>("MaXacNhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianHetHan")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("xacNhanEmails");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.BaiHoc", b =>
                {
                    b.HasOne("WebCourseManagement_Models.Entities.ChuongKhoaHoc", "ChuongKhoaHoc")
                        .WithMany("BaiHocs")
                        .HasForeignKey("ChuongKhoaHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebCourseManagement_Models.Entities.LoaiBaiHoc", "LoaiBaiHoc")
                        .WithMany()
                        .HasForeignKey("LoaiBaiHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebCourseManagement_Models.Entities.TrangThaiBaiHoc", "TrangThaiBaiHoc")
                        .WithMany()
                        .HasForeignKey("TrangThaiBaiHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChuongKhoaHoc");

                    b.Navigation("LoaiBaiHoc");

                    b.Navigation("TrangThaiBaiHoc");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.BaiViet", b =>
                {
                    b.HasOne("WebCourseManagement_Models.Entities.NguoiDung", "NguoiDungTaoBai")
                        .WithMany()
                        .HasForeignKey("NguoiDungTaoBaiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebCourseManagement_Models.Entities.TrangThaiBaiViet", "TrangThaiBaiViet")
                        .WithMany()
                        .HasForeignKey("TrangThaiBaiVietId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDungTaoBai");

                    b.Navigation("TrangThaiBaiViet");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.BaoCao", b =>
                {
                    b.HasOne("WebCourseManagement_Models.Entities.LoaiBaoCao", "LoaiBaoCao")
                        .WithMany()
                        .HasForeignKey("LoaiBaoCaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebCourseManagement_Models.Entities.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiBaoCao");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.BinhLuanBaiHoc", b =>
                {
                    b.HasOne("WebCourseManagement_Models.Entities.BaiHoc", "BaiHoc")
                        .WithMany("BinhLuanBaiHocs")
                        .HasForeignKey("BaiHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebCourseManagement_Models.Entities.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungId");

                    b.HasOne("WebCourseManagement_Models.Entities.TrangThaiBinhLuan", "TrangThaiBinhLuan")
                        .WithMany("BinhLuanBaiHocs")
                        .HasForeignKey("TrangThaiBinhLuanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaiHoc");

                    b.Navigation("NguoiDung");

                    b.Navigation("TrangThaiBinhLuan");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.BinhLuanBaiViet", b =>
                {
                    b.HasOne("WebCourseManagement_Models.Entities.BaiViet", "BaiViet")
                        .WithMany()
                        .HasForeignKey("BaiVietId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebCourseManagement_Models.Entities.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungId");

                    b.HasOne("WebCourseManagement_Models.Entities.TrangThaiBinhLuan", "TrangThaiBinhLuan")
                        .WithMany("BinhLuanBaiViets")
                        .HasForeignKey("TrangThaiBinhLuanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaiViet");

                    b.Navigation("NguoiDung");

                    b.Navigation("TrangThaiBinhLuan");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.Blog", b =>
                {
                    b.HasOne("WebCourseManagement_Models.Entities.LoaiBlog", "LoaiBlog")
                        .WithMany("Blogs")
                        .HasForeignKey("LoaiBlogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebCourseManagement_Models.Entities.NguoiDung", "NguoiDangBai")
                        .WithMany()
                        .HasForeignKey("NguoiDangBaiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebCourseManagement_Models.Entities.TrangThaiBlog", "TrangThaiBlog")
                        .WithMany("Blogs")
                        .HasForeignKey("TrangThaiBlogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiBlog");

                    b.Navigation("NguoiDangBai");

                    b.Navigation("TrangThaiBlog");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.ChuongKhoaHoc", b =>
                {
                    b.HasOne("WebCourseManagement_Models.Entities.KhoaHoc", "KhoaHoc")
                        .WithMany("ChuongKhoaHocs")
                        .HasForeignKey("KhoaHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhoaHoc");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.CodeDaNgonNgu", b =>
                {
                    b.HasOne("WebCourseManagement_Models.Entities.NgonNgu", "NgonNgu")
                        .WithMany()
                        .HasForeignKey("NgonNguId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebCourseManagement_Models.Entities.ThucHanh", "ThucHanh")
                        .WithMany()
                        .HasForeignKey("ThucHanhId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NgonNgu");

                    b.Navigation("ThucHanh");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.DanhHieuNguoiDung", b =>
                {
                    b.HasOne("WebCourseManagement_Models.Entities.DanhHieu", "DanhHieu")
                        .WithMany()
                        .HasForeignKey("DanhHieuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebCourseManagement_Models.Entities.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DanhHieu");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.DatCauHoi", b =>
                {
                    b.HasOne("WebCourseManagement_Models.Entities.BaiHoc", "BaiHoc")
                        .WithMany()
                        .HasForeignKey("BaiHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaiHoc");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.DiemKiemTraBaiHocCuaNguoiDung", b =>
                {
                    b.HasOne("WebCourseManagement_Models.Entities.BaiHoc", "BaiHoc")
                        .WithMany()
                        .HasForeignKey("BaiHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebCourseManagement_Models.Entities.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaiHoc");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.HoanThanhThucHanh", b =>
                {
                    b.HasOne("WebCourseManagement_Models.Entities.ThucHanh", "BaiHocThucHanh")
                        .WithMany()
                        .HasForeignKey("BaiHocThucHanhId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebCourseManagement_Models.Entities.NgonNgu", "NgonNgu")
                        .WithMany()
                        .HasForeignKey("NgonNguId");

                    b.HasOne("WebCourseManagement_Models.Entities.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaiHocThucHanh");

                    b.Navigation("NgonNgu");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.HoanThanhTraLoiCauHoi", b =>
                {
                    b.HasOne("WebCourseManagement_Models.Entities.DatCauHoi", "CauHoi")
                        .WithMany()
                        .HasForeignKey("CauHoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebCourseManagement_Models.Entities.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CauHoi");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.KhoaHoc", b =>
                {
                    b.HasOne("WebCourseManagement_Models.Entities.LoaiKhoaHoc", "LoaiKhoaHoc")
                        .WithMany("KhoaHocs")
                        .HasForeignKey("LoaiKhoaHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebCourseManagement_Models.Entities.NguoiDung", "NguoiTao")
                        .WithMany()
                        .HasForeignKey("NguoiTaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebCourseManagement_Models.Entities.TrangThaiKhoaHoc", "TrangThaiKhoaHoc")
                        .WithMany()
                        .HasForeignKey("TrangThaiKhoaHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiKhoaHoc");

                    b.Navigation("NguoiTao");

                    b.Navigation("TrangThaiKhoaHoc");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.KhoaHocCuaNguoiDung", b =>
                {
                    b.HasOne("WebCourseManagement_Models.Entities.BaiHoc", "BaiHoc")
                        .WithMany()
                        .HasForeignKey("BaiHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebCourseManagement_Models.Entities.KhoaHoc", "KhoaHoc")
                        .WithMany()
                        .HasForeignKey("KhoaHocId");

                    b.HasOne("WebCourseManagement_Models.Entities.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungId");

                    b.Navigation("BaiHoc");

                    b.Navigation("KhoaHoc");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.KinhNghiem", b =>
                {
                    b.HasOne("WebCourseManagement_Models.Entities.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.KinhNghiemHocTap", b =>
                {
                    b.HasOne("WebCourseManagement_Models.Entities.ChuyenNganh", "ChuyenNganh")
                        .WithMany()
                        .HasForeignKey("ChuyenNganhId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebCourseManagement_Models.Entities.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebCourseManagement_Models.Entities.TruongHoc", "TruongHoc")
                        .WithMany()
                        .HasForeignKey("TruongHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChuyenNganh");

                    b.Navigation("NguoiDung");

                    b.Navigation("TruongHoc");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.LienHe", b =>
                {
                    b.HasOne("WebCourseManagement_Models.Entities.NguoiDung", "NguoiLienHe")
                        .WithMany()
                        .HasForeignKey("NguoiLienHeId");

                    b.Navigation("NguoiLienHe");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.NguoiDung", b =>
                {
                    b.HasOne("WebCourseManagement_Models.Entities.DanhMucNguoiDung", "DanhMucNguoiDung")
                        .WithMany()
                        .HasForeignKey("DanhMucNguoiDungId");

                    b.HasOne("WebCourseManagement_Models.Entities.QuanHuyen", "QuanHuyen")
                        .WithMany()
                        .HasForeignKey("QuanHuyenId");

                    b.HasOne("WebCourseManagement_Models.Entities.QuyenHan", "QuyenHan")
                        .WithMany()
                        .HasForeignKey("QuyenHanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebCourseManagement_Models.Entities.TinhThanh", "TinhThanh")
                        .WithMany()
                        .HasForeignKey("TinhThanhId");

                    b.HasOne("WebCourseManagement_Models.Entities.TrangThaiNguoiDung", "TrangThaiNguoiDung")
                        .WithMany()
                        .HasForeignKey("TrangThaiNguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebCourseManagement_Models.Entities.XaPhuong", "XaPhuong")
                        .WithMany()
                        .HasForeignKey("XaPhuongId");

                    b.Navigation("DanhMucNguoiDung");

                    b.Navigation("QuanHuyen");

                    b.Navigation("QuyenHan");

                    b.Navigation("TinhThanh");

                    b.Navigation("TrangThaiNguoiDung");

                    b.Navigation("XaPhuong");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.NguoiDungGhiChuBaiHoc", b =>
                {
                    b.HasOne("WebCourseManagement_Models.Entities.DiemKiemTraBaiHocCuaNguoiDung", "DiemKiemTraBaiHoc")
                        .WithMany()
                        .HasForeignKey("DiemKiemTraBaiHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiemKiemTraBaiHoc");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.NguoiDungThichBaiViet", b =>
                {
                    b.HasOne("WebCourseManagement_Models.Entities.BaiViet", "BaiViet")
                        .WithMany()
                        .HasForeignKey("BaiVietId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebCourseManagement_Models.Entities.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaiViet");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.NguoiDungThichBinhLuanBaiHoc", b =>
                {
                    b.HasOne("WebCourseManagement_Models.Entities.BinhLuanBaiHoc", "BinhLuanBaiHoc")
                        .WithMany()
                        .HasForeignKey("BinhLuanBaiHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebCourseManagement_Models.Entities.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BinhLuanBaiHoc");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.NguoiDungThichBinhLuanBaiViet", b =>
                {
                    b.HasOne("WebCourseManagement_Models.Entities.BinhLuanBaiViet", "BinhLuanBaiViet")
                        .WithMany()
                        .HasForeignKey("BinhLuanBaiVietId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebCourseManagement_Models.Entities.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BinhLuanBaiViet");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.PhanHoc", b =>
                {
                    b.HasOne("WebCourseManagement_Models.Entities.BaiHoc", "BaiHoc")
                        .WithMany()
                        .HasForeignKey("BaiHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebCourseManagement_Models.Entities.ChuongKhoaHoc", "ChuongKhoaHoc")
                        .WithMany()
                        .HasForeignKey("ChuongKhoaHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaiHoc");

                    b.Navigation("ChuongKhoaHoc");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.QuanHuyen", b =>
                {
                    b.HasOne("WebCourseManagement_Models.Entities.TinhThanh", "TinhThanh")
                        .WithMany()
                        .HasForeignKey("TinhThanhId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TinhThanh");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.RefreshToken", b =>
                {
                    b.HasOne("WebCourseManagement_Models.Entities.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.TestCase", b =>
                {
                    b.HasOne("WebCourseManagement_Models.Entities.ThucHanh", "ThucHanh")
                        .WithMany("TestCases")
                        .HasForeignKey("ThucHanhId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ThucHanh");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.ThongBao", b =>
                {
                    b.HasOne("WebCourseManagement_Models.Entities.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.ThongBaoTrangChu", b =>
                {
                    b.HasOne("WebCourseManagement_Models.Entities.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.ThucHanh", b =>
                {
                    b.HasOne("WebCourseManagement_Models.Entities.BaiHoc", "BaiHoc")
                        .WithMany()
                        .HasForeignKey("BaiHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebCourseManagement_Models.Entities.NgonNgu", "NgonNguMacDinh")
                        .WithMany()
                        .HasForeignKey("NgonNguMacDinhId");

                    b.Navigation("BaiHoc");

                    b.Navigation("NgonNguMacDinh");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.TruongHoc", b =>
                {
                    b.HasOne("WebCourseManagement_Models.Entities.LoaiTruongHoc", "LoaiTruongHoc")
                        .WithMany()
                        .HasForeignKey("LoaiTruongHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiTruongHoc");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.VideoBaiGiang", b =>
                {
                    b.HasOne("WebCourseManagement_Models.Entities.BaiHoc", "BaiHoc")
                        .WithMany()
                        .HasForeignKey("BaiHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaiHoc");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.VideoHoanThanh", b =>
                {
                    b.HasOne("WebCourseManagement_Models.Entities.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebCourseManagement_Models.Entities.VideoBaiGiang", "VideoBaiGiang")
                        .WithMany()
                        .HasForeignKey("VideoBaiGiangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");

                    b.Navigation("VideoBaiGiang");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.XaPhuong", b =>
                {
                    b.HasOne("WebCourseManagement_Models.Entities.QuanHuyen", "QuanHuyen")
                        .WithMany()
                        .HasForeignKey("QuanHuyenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuanHuyen");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.XacNhanEmail", b =>
                {
                    b.HasOne("WebCourseManagement_Models.Entities.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.BaiHoc", b =>
                {
                    b.Navigation("BinhLuanBaiHocs");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.ChuongKhoaHoc", b =>
                {
                    b.Navigation("BaiHocs");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.KhoaHoc", b =>
                {
                    b.Navigation("ChuongKhoaHocs");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.LoaiBlog", b =>
                {
                    b.Navigation("Blogs");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.LoaiKhoaHoc", b =>
                {
                    b.Navigation("KhoaHocs");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.ThucHanh", b =>
                {
                    b.Navigation("TestCases");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.TrangThaiBinhLuan", b =>
                {
                    b.Navigation("BinhLuanBaiHocs");

                    b.Navigation("BinhLuanBaiViets");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.TrangThaiBlog", b =>
                {
                    b.Navigation("Blogs");
                });
#pragma warning restore 612, 618
        }
    }
}
