// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebCourseManagement_Models.DataContexts;

#nullable disable

namespace WebCourseManagement_Models.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240313045342_upchuong")]
    partial class upchuong
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebCourseManagement_Models.Entities.BaiHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChuongHocId")
                        .HasColumnType("int");

                    b.Property<string>("MoTaBaiHoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenBaiHoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ThoiGianCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("ThoiLuongVideo")
                        .HasColumnType("int");

                    b.Property<int>("TrangThaiBaiHocId")
                        .HasColumnType("int");

                    b.Property<string>("VideoBaiHoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChuongHocId");

                    b.HasIndex("TrangThaiBaiHocId");

                    b.ToTable("baiHocs");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.BaiViet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnhBaiViet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LoaiBaiVietId")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NguoiTaoBaiVietId")
                        .HasColumnType("int");

                    b.Property<int>("SoLuotBinhLuan")
                        .HasColumnType("int");

                    b.Property<int>("SoLuotThich")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ThoiGianCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianXoa")
                        .HasColumnType("datetime2");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThaiBaiVietId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LoaiBaiVietId");

                    b.HasIndex("NguoiTaoBaiVietId");

                    b.HasIndex("TrangThaiBaiVietId");

                    b.ToTable("baiViets");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.Banner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnhBanner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("banners");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.BaoCao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BinhLuanId")
                        .HasColumnType("int");

                    b.Property<bool?>("DaViPham")
                        .HasColumnType("bit");

                    b.Property<bool?>("DaXacMinh")
                        .HasColumnType("bit");

                    b.Property<string>("GhiChuBaoCao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LoaiBaoCaoId")
                        .HasColumnType("int");

                    b.Property<int>("LoaiBinhLuan")
                        .HasColumnType("int");

                    b.Property<int>("NguoiGuiBaoCaoId")
                        .HasColumnType("int");

                    b.Property<int>("NguoiViPhamId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianGuiBaoCao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianXacMinh")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LoaiBaoCaoId");

                    b.HasIndex("NguoiGuiBaoCaoId");

                    b.ToTable("baoCaos");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.BinhLuanBaiHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BaiHocId")
                        .HasColumnType("int");

                    b.Property<int?>("BinhLuanGocId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("NguoiBinhLuanId")
                        .HasColumnType("int");

                    b.Property<string>("NoiDungBinhLuan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoLuotThich")
                        .HasColumnType("int");

                    b.Property<int>("SoLuotTraLoiBinhLuan")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ThoiGianCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianXoa")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrangThaiBinhLuanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BaiHocId");

                    b.HasIndex("NguoiBinhLuanId");

                    b.HasIndex("TrangThaiBinhLuanId");

                    b.ToTable("binhLuanBaiHocs");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.BinhLuanBaiViet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BaiVietId")
                        .HasColumnType("int");

                    b.Property<int?>("BinhLuanGocId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("NguoiBinhLuanId")
                        .HasColumnType("int");

                    b.Property<string>("NoiDungBinhLuan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoLuotThich")
                        .HasColumnType("int");

                    b.Property<int>("SoLuotTraLoiBinhLuan")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ThoiGianCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianXoa")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrangThaiBinhLuanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BaiVietId");

                    b.HasIndex("NguoiBinhLuanId");

                    b.HasIndex("TrangThaiBinhLuanId");

                    b.ToTable("binhLuanBaiViets");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.CauTraLoi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CauHoiId")
                        .HasColumnType("int");

                    b.Property<string>("CauTraLoiChiTiet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NguoiTraLoiId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianTraLoi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CauHoiId");

                    b.HasIndex("NguoiTraLoiId");

                    b.ToTable("cauTraLois");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.ChuongHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnhChuongHoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("KhoaHocId")
                        .HasColumnType("int");

                    b.Property<int>("SoBaiHocTrongChuong")
                        .HasColumnType("int");

                    b.Property<string>("TenChuong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ThoiGianCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("TongThoiGianHocTrongChuong")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KhoaHocId");

                    b.ToTable("chuongHocs");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.CodeDaNgonNgu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CallTestCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodeKhoiDau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NgonNguId")
                        .HasColumnType("int");

                    b.Property<int>("ThucHanhId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NgonNguId");

                    b.HasIndex("ThucHanhId");

                    b.ToTable("codeDaNgonNgus");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.DanhGia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("SoSao")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("danhGias");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.DatCauHoi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BaiHocId")
                        .HasColumnType("int");

                    b.Property<string>("CauTraLoi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoCauTraLoi")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BaiHocId");

                    b.ToTable("datCauHois");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.HoaDonDangKy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("KhoaHocId")
                        .HasColumnType("int");

                    b.Property<string>("MaGiaoDich")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TrangThaiHoaDonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KhoaHocId");

                    b.HasIndex("NguoiDungId");

                    b.HasIndex("TrangThaiHoaDonId");

                    b.ToTable("hoaDonDangKies");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.HoanThanhThucHanh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("NgonNguId")
                        .HasColumnType("int");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianHoanThanh")
                        .HasColumnType("datetime2");

                    b.Property<int>("ThucHanhId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NgonNguId");

                    b.HasIndex("NguoiDungId");

                    b.HasIndex("ThucHanhId");

                    b.ToTable("hoanThanhThucHanhs");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.KhoaHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnhKhoaHoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("DaXoa")
                        .HasColumnType("bit");

                    b.Property<decimal>("GiaKhoaHoc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("GiaKhoaHocThucTe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("LoaiKhoaHocId")
                        .HasColumnType("int");

                    b.Property<string>("MoTaKhoaHoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiTaoId")
                        .HasColumnType("int");

                    b.Property<decimal?>("PhanTramGiamGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SoHocVienDaHoanThanh")
                        .HasColumnType("int");

                    b.Property<string>("TieuDeKhoaHoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TongThoiGianKhoaHoc")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LoaiKhoaHocId");

                    b.ToTable("khoaHocs");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.KhoaHocCuaNguoiDung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BaiHocHienTaiId")
                        .HasColumnType("int");

                    b.Property<bool?>("DaHoanThanh")
                        .HasColumnType("bit");

                    b.Property<int?>("DanhGiaId")
                        .HasColumnType("int");

                    b.Property<int>("KhoaHocId")
                        .HasColumnType("int");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<double>("PhanTramHoanThanh")
                        .HasColumnType("float");

                    b.Property<DateTime>("ThoiGianDangKy")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BaiHocHienTaiId");

                    b.HasIndex("DanhGiaId");

                    b.HasIndex("KhoaHocId");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("khoaHocCuaNguoiDungs");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.LienHeAdmin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("DaLienHe")
                        .HasColumnType("bit");

                    b.Property<int>("NguoiLienHeId")
                        .HasColumnType("int");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNguoiLienHe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGianLienHe")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NguoiLienHeId");

                    b.ToTable("lienHeAdmins");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.LoaiBaiViet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenLoaiBaiViet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("loaiBaiViets");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.LoaiBaoCao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenLoaiBaoCao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("loaiBaoCaos");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.LoaiKhoaHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenLoaiKhoaHoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("loaiKhoaHocs");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.NgonNgu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenNgonNgu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ngonNgus");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.NguoiDung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnhDaiDien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("DaKhoa")
                        .HasColumnType("bit");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GioiTinh")
                        .HasColumnType("int");

                    b.Property<string>("HoVaTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<int?>("QuanHuyenId")
                        .HasColumnType("int");

                    b.Property<int>("QuyenHanId")
                        .HasColumnType("int");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SoLanViPham")
                        .HasColumnType("int");

                    b.Property<string>("TaiKhoan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ThoiGianCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianKhoa")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianMoKhoa")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianXoa")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TinhThanhId")
                        .HasColumnType("int");

                    b.Property<int>("TrangThaiNguoiDungId")
                        .HasColumnType("int");

                    b.Property<int?>("XaPhuongId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuanHuyenId");

                    b.HasIndex("QuyenHanId");

                    b.HasIndex("TinhThanhId");

                    b.HasIndex("TrangThaiNguoiDungId");

                    b.HasIndex("XaPhuongId");

                    b.ToTable("nguoiDungs");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.NguoiDungThichBaiViet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BaiVietId")
                        .HasColumnType("int");

                    b.Property<bool?>("DaThich")
                        .HasColumnType("bit");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ThoiGianBoThich")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianThich")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BaiVietId");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("nguoiDungThichBaiViets");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.NguoiDungThichBinhLuanBaiHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BinhLuanBaiHocId")
                        .HasColumnType("int");

                    b.Property<bool?>("DaThich")
                        .HasColumnType("bit");

                    b.Property<int>("NguoiDungThichBinhLuanId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ThoiGianBoThich")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianThich")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BinhLuanBaiHocId");

                    b.HasIndex("NguoiDungThichBinhLuanId");

                    b.ToTable("nguoiDungThichBinhLuanBaiHocs");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.NguoiDungThichBinhLuanBaiViet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BinhLuanBaiVietId")
                        .HasColumnType("int");

                    b.Property<bool?>("DaThich")
                        .HasColumnType("bit");

                    b.Property<int>("NguoiDungThichBinhLuanId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ThoiGianBoThich")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianThich")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BinhLuanBaiVietId");

                    b.HasIndex("NguoiDungThichBinhLuanId");

                    b.ToTable("nguoiDungThichBinhLuanBaiViets");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.QuanHuyen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenQuanHuyen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TinhThanhId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TinhThanhId");

                    b.ToTable("quanHuyens");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.QuyenHan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MaQuyenHan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenQuyenHan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("quyenHans");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianHetHan")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("refreshTokens");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.TestCase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChiTietDauVao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodeDauVao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("KhoaTestCase")
                        .HasColumnType("bit");

                    b.Property<string>("MongDoiDauRa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ThucHanhId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ThucHanhId");

                    b.ToTable("testCases");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.ThongBao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("DaXemThongBao")
                        .HasColumnType("bit");

                    b.Property<bool>("HeThongThongBao")
                        .HasColumnType("bit");

                    b.Property<string>("LinkThongBao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NguoiDungGuiThongBaoId")
                        .HasColumnType("int");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<string>("NoiDungThongBao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGianThongBao")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("thongBaos");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.ThongBaoTrangChu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnhThongBao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGianThongBao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("thongBaoTrangChus");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.ThucHanh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BaiHocId")
                        .HasColumnType("int");

                    b.Property<string>("CallTestCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChiTietDeBai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodeDauVao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodeKhoiDau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeBai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GiaiThich")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoiY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("HoTroDaNgonNgu")
                        .HasColumnType("bit");

                    b.Property<string>("MongDoiDauRa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NgonNguMacDinhId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BaiHocId");

                    b.HasIndex("NgonNguMacDinhId");

                    b.ToTable("thucHanhs");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.TinhThanh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenTinhThanh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tinhThanhs");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.TrangThaiBaiHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenTrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("trangThaiBaiHocs");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.TrangThaiBaiViet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenTrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("trangThaiBaiViets");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.TrangThaiBinhLuan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenTrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("trangThaiBinhLuans");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.TrangThaiHoaDon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenTrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("trangThaiHoaDons");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.TrangThaiNguoiDung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MaTrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenTrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("trangThaiNguoiDungs");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.XaPhuong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("QuanHuyenId")
                        .HasColumnType("int");

                    b.Property<string>("TenXaPhuong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("QuanHuyenId");

                    b.ToTable("xaPhuongs");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.XacNhanEmail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("DaXacNhan")
                        .HasColumnType("bit");

                    b.Property<string>("MaXacNhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianHetHan")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("xacNhanEmails");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.BaiHoc", b =>
                {
                    b.HasOne("WebCourseManagement_Models.Entities.ChuongHoc", "ChuongHoc")
                        .WithMany("BaiHocs")
                        .HasForeignKey("ChuongHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebCourseManagement_Models.Entities.TrangThaiBaiHoc", "TrangThaiBaiHoc")
                        .WithMany()
                        .HasForeignKey("TrangThaiBaiHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChuongHoc");

                    b.Navigation("TrangThaiBaiHoc");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.BaiViet", b =>
                {
                    b.HasOne("WebCourseManagement_Models.Entities.LoaiBaiViet", "LoaiBaiViet")
                        .WithMany("BaiViets")
                        .HasForeignKey("LoaiBaiVietId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebCourseManagement_Models.Entities.NguoiDung", "NguoiTaoBaiViet")
                        .WithMany("BaiViets")
                        .HasForeignKey("NguoiTaoBaiVietId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebCourseManagement_Models.Entities.TrangThaiBaiViet", "TrangThaiBaiViet")
                        .WithMany()
                        .HasForeignKey("TrangThaiBaiVietId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiBaiViet");

                    b.Navigation("NguoiTaoBaiViet");

                    b.Navigation("TrangThaiBaiViet");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.BaoCao", b =>
                {
                    b.HasOne("WebCourseManagement_Models.Entities.LoaiBaoCao", "LoaiBaoCao")
                        .WithMany()
                        .HasForeignKey("LoaiBaoCaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebCourseManagement_Models.Entities.NguoiDung", "NguoiGuiBaoCao")
                        .WithMany("BaoCaos")
                        .HasForeignKey("NguoiGuiBaoCaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiBaoCao");

                    b.Navigation("NguoiGuiBaoCao");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.BinhLuanBaiHoc", b =>
                {
                    b.HasOne("WebCourseManagement_Models.Entities.BaiHoc", "BaiHoc")
                        .WithMany("BinhLuanBaiHocs")
                        .HasForeignKey("BaiHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebCourseManagement_Models.Entities.NguoiDung", "NguoiBinhLuan")
                        .WithMany("BinhLuanBaiHocs")
                        .HasForeignKey("NguoiBinhLuanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebCourseManagement_Models.Entities.TrangThaiBinhLuan", "TrangThaiBinhLuan")
                        .WithMany()
                        .HasForeignKey("TrangThaiBinhLuanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaiHoc");

                    b.Navigation("NguoiBinhLuan");

                    b.Navigation("TrangThaiBinhLuan");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.BinhLuanBaiViet", b =>
                {
                    b.HasOne("WebCourseManagement_Models.Entities.BaiViet", "BaiViet")
                        .WithMany("BinhLuanBaiViets")
                        .HasForeignKey("BaiVietId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebCourseManagement_Models.Entities.NguoiDung", "NguoiBinhLuan")
                        .WithMany("BinhLuanBaiViets")
                        .HasForeignKey("NguoiBinhLuanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebCourseManagement_Models.Entities.TrangThaiBinhLuan", "TrangThaiBinhLuan")
                        .WithMany()
                        .HasForeignKey("TrangThaiBinhLuanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaiViet");

                    b.Navigation("NguoiBinhLuan");

                    b.Navigation("TrangThaiBinhLuan");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.CauTraLoi", b =>
                {
                    b.HasOne("WebCourseManagement_Models.Entities.DatCauHoi", "CauHoi")
                        .WithMany("CauTraLois")
                        .HasForeignKey("CauHoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebCourseManagement_Models.Entities.NguoiDung", "NguoiTraLoi")
                        .WithMany("CauTraLois")
                        .HasForeignKey("NguoiTraLoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CauHoi");

                    b.Navigation("NguoiTraLoi");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.ChuongHoc", b =>
                {
                    b.HasOne("WebCourseManagement_Models.Entities.KhoaHoc", "KhoaHoc")
                        .WithMany("ChuongHocs")
                        .HasForeignKey("KhoaHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhoaHoc");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.CodeDaNgonNgu", b =>
                {
                    b.HasOne("WebCourseManagement_Models.Entities.NgonNgu", "NgonNgu")
                        .WithMany()
                        .HasForeignKey("NgonNguId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebCourseManagement_Models.Entities.ThucHanh", "ThucHanh")
                        .WithMany()
                        .HasForeignKey("ThucHanhId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NgonNgu");

                    b.Navigation("ThucHanh");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.DatCauHoi", b =>
                {
                    b.HasOne("WebCourseManagement_Models.Entities.BaiHoc", "BaiHoc")
                        .WithMany("DatCauHois")
                        .HasForeignKey("BaiHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaiHoc");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.HoaDonDangKy", b =>
                {
                    b.HasOne("WebCourseManagement_Models.Entities.KhoaHoc", "KhoaHoc")
                        .WithMany()
                        .HasForeignKey("KhoaHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebCourseManagement_Models.Entities.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebCourseManagement_Models.Entities.TrangThaiHoaDon", "TrangThaiHoaDon")
                        .WithMany()
                        .HasForeignKey("TrangThaiHoaDonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhoaHoc");

                    b.Navigation("NguoiDung");

                    b.Navigation("TrangThaiHoaDon");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.HoanThanhThucHanh", b =>
                {
                    b.HasOne("WebCourseManagement_Models.Entities.NgonNgu", "NgonNgu")
                        .WithMany()
                        .HasForeignKey("NgonNguId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebCourseManagement_Models.Entities.NguoiDung", "NguoiDung")
                        .WithMany("HoanThanhThucHanhs")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebCourseManagement_Models.Entities.ThucHanh", "ThucHanh")
                        .WithMany()
                        .HasForeignKey("ThucHanhId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NgonNgu");

                    b.Navigation("NguoiDung");

                    b.Navigation("ThucHanh");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.KhoaHoc", b =>
                {
                    b.HasOne("WebCourseManagement_Models.Entities.LoaiKhoaHoc", "LoaiKhoaHoc")
                        .WithMany("KhoaHocs")
                        .HasForeignKey("LoaiKhoaHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiKhoaHoc");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.KhoaHocCuaNguoiDung", b =>
                {
                    b.HasOne("WebCourseManagement_Models.Entities.BaiHoc", "BaiHocHienTai")
                        .WithMany("KhoaHocCuaNguoiDungs")
                        .HasForeignKey("BaiHocHienTaiId");

                    b.HasOne("WebCourseManagement_Models.Entities.DanhGia", "DanhGia")
                        .WithMany()
                        .HasForeignKey("DanhGiaId");

                    b.HasOne("WebCourseManagement_Models.Entities.KhoaHoc", "KhoaHoc")
                        .WithMany("KhoaHocCuaNguoiDungs")
                        .HasForeignKey("KhoaHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebCourseManagement_Models.Entities.NguoiDung", "NguoiDung")
                        .WithMany("KhoaHocCuaNguoiDungs")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaiHocHienTai");

                    b.Navigation("DanhGia");

                    b.Navigation("KhoaHoc");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.LienHeAdmin", b =>
                {
                    b.HasOne("WebCourseManagement_Models.Entities.NguoiDung", "NguoiLienHe")
                        .WithMany("LienHeAdmins")
                        .HasForeignKey("NguoiLienHeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiLienHe");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.NguoiDung", b =>
                {
                    b.HasOne("WebCourseManagement_Models.Entities.QuanHuyen", "QuanHuyen")
                        .WithMany("NguoiDungs")
                        .HasForeignKey("QuanHuyenId");

                    b.HasOne("WebCourseManagement_Models.Entities.QuyenHan", "QuyenHan")
                        .WithMany()
                        .HasForeignKey("QuyenHanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebCourseManagement_Models.Entities.TinhThanh", "TinhThanh")
                        .WithMany("NguoiDungs")
                        .HasForeignKey("TinhThanhId");

                    b.HasOne("WebCourseManagement_Models.Entities.TrangThaiNguoiDung", "TrangThaiNguoiDung")
                        .WithMany()
                        .HasForeignKey("TrangThaiNguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebCourseManagement_Models.Entities.XaPhuong", "XaPhuong")
                        .WithMany("NguoiDungs")
                        .HasForeignKey("XaPhuongId");

                    b.Navigation("QuanHuyen");

                    b.Navigation("QuyenHan");

                    b.Navigation("TinhThanh");

                    b.Navigation("TrangThaiNguoiDung");

                    b.Navigation("XaPhuong");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.NguoiDungThichBaiViet", b =>
                {
                    b.HasOne("WebCourseManagement_Models.Entities.BaiViet", "BaiViet")
                        .WithMany("NguoiDungThichBaiViets")
                        .HasForeignKey("BaiVietId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebCourseManagement_Models.Entities.NguoiDung", "NguoiDung")
                        .WithMany("NguoiDungThichBaiViets")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaiViet");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.NguoiDungThichBinhLuanBaiHoc", b =>
                {
                    b.HasOne("WebCourseManagement_Models.Entities.BinhLuanBaiHoc", "BinhLuanBaiHoc")
                        .WithMany("NguoiDungThichBinhLuanBaiHocs")
                        .HasForeignKey("BinhLuanBaiHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebCourseManagement_Models.Entities.NguoiDung", "NguoiDungThichBinhLuan")
                        .WithMany("NguoiDungThichBinhLuanBaiHocs")
                        .HasForeignKey("NguoiDungThichBinhLuanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BinhLuanBaiHoc");

                    b.Navigation("NguoiDungThichBinhLuan");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.NguoiDungThichBinhLuanBaiViet", b =>
                {
                    b.HasOne("WebCourseManagement_Models.Entities.BinhLuanBaiViet", "BinhLuanBaiViet")
                        .WithMany("NguoiDungThichBinhLuanBaiViets")
                        .HasForeignKey("BinhLuanBaiVietId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebCourseManagement_Models.Entities.NguoiDung", "NguoiDungThichBinhLuan")
                        .WithMany("NguoiDungThichBinhLuanBaiViets")
                        .HasForeignKey("NguoiDungThichBinhLuanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BinhLuanBaiViet");

                    b.Navigation("NguoiDungThichBinhLuan");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.QuanHuyen", b =>
                {
                    b.HasOne("WebCourseManagement_Models.Entities.TinhThanh", "TinhThanh")
                        .WithMany("QuanHuyens")
                        .HasForeignKey("TinhThanhId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TinhThanh");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.TestCase", b =>
                {
                    b.HasOne("WebCourseManagement_Models.Entities.ThucHanh", "ThucHanh")
                        .WithMany()
                        .HasForeignKey("ThucHanhId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ThucHanh");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.ThongBao", b =>
                {
                    b.HasOne("WebCourseManagement_Models.Entities.NguoiDung", "NguoiDung")
                        .WithMany("ThongBaos")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.ThongBaoTrangChu", b =>
                {
                    b.HasOne("WebCourseManagement_Models.Entities.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.ThucHanh", b =>
                {
                    b.HasOne("WebCourseManagement_Models.Entities.BaiHoc", "BaiHoc")
                        .WithMany("ThucHanhs")
                        .HasForeignKey("BaiHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebCourseManagement_Models.Entities.NgonNgu", "NgonNguMacDinh")
                        .WithMany()
                        .HasForeignKey("NgonNguMacDinhId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaiHoc");

                    b.Navigation("NgonNguMacDinh");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.XaPhuong", b =>
                {
                    b.HasOne("WebCourseManagement_Models.Entities.QuanHuyen", "QuanHuyen")
                        .WithMany("XaPhuongs")
                        .HasForeignKey("QuanHuyenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuanHuyen");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.BaiHoc", b =>
                {
                    b.Navigation("BinhLuanBaiHocs");

                    b.Navigation("DatCauHois");

                    b.Navigation("KhoaHocCuaNguoiDungs");

                    b.Navigation("ThucHanhs");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.BaiViet", b =>
                {
                    b.Navigation("BinhLuanBaiViets");

                    b.Navigation("NguoiDungThichBaiViets");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.BinhLuanBaiHoc", b =>
                {
                    b.Navigation("NguoiDungThichBinhLuanBaiHocs");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.BinhLuanBaiViet", b =>
                {
                    b.Navigation("NguoiDungThichBinhLuanBaiViets");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.ChuongHoc", b =>
                {
                    b.Navigation("BaiHocs");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.DatCauHoi", b =>
                {
                    b.Navigation("CauTraLois");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.KhoaHoc", b =>
                {
                    b.Navigation("ChuongHocs");

                    b.Navigation("KhoaHocCuaNguoiDungs");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.LoaiBaiViet", b =>
                {
                    b.Navigation("BaiViets");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.LoaiKhoaHoc", b =>
                {
                    b.Navigation("KhoaHocs");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.NguoiDung", b =>
                {
                    b.Navigation("BaiViets");

                    b.Navigation("BaoCaos");

                    b.Navigation("BinhLuanBaiHocs");

                    b.Navigation("BinhLuanBaiViets");

                    b.Navigation("CauTraLois");

                    b.Navigation("HoanThanhThucHanhs");

                    b.Navigation("KhoaHocCuaNguoiDungs");

                    b.Navigation("LienHeAdmins");

                    b.Navigation("NguoiDungThichBaiViets");

                    b.Navigation("NguoiDungThichBinhLuanBaiHocs");

                    b.Navigation("NguoiDungThichBinhLuanBaiViets");

                    b.Navigation("ThongBaos");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.QuanHuyen", b =>
                {
                    b.Navigation("NguoiDungs");

                    b.Navigation("XaPhuongs");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.TinhThanh", b =>
                {
                    b.Navigation("NguoiDungs");

                    b.Navigation("QuanHuyens");
                });

            modelBuilder.Entity("WebCourseManagement_Models.Entities.XaPhuong", b =>
                {
                    b.Navigation("NguoiDungs");
                });
#pragma warning restore 612, 618
        }
    }
}
